const EXPERTIES = [
  {
    title: "Demolition Planning Services",
    content:
      "Pre-Bid Proof of Concept: DEEPAM ENGINEERING will work with your team to provide a proof of concept for your demolition to utilize during the bidding process with your client.",
  },
  {
    title: "Demolition Design",
    content:
      "DEEPAM ENGINEERING will work with your team to design a safe and efficient demolition based on your project requirements. Multiple demolition plans can be safely and efficiently evaluated virtually without expending resources on the job-site that might result in loss of life or property.",
  },
  {
    title: "Demolition Analysis",
    content:
      "Given the actual demolition plan, DEEPAM ENGINEERING can provide an accurate analysis of the proposed plan. If the proposed demolition plan indicates the possibility of a mishap or hazard, we can suggest alternative scenarios or modifications to the planned approach. we can also provide engaging visuals early on in the bidding process for encouraging plan approval or for display in public forums.",
  },
  {
    title: "Weakening Analysis",
    content:
      "Provided with a weakening plan, we can model and analyse the effects of the proposed weakening on the structure. This can also include a wind and/or seismic analysis if the structure resides in a high wind or seismic area to ensure that the structure does not fail prematurely.",
  },
  {
    title: "Seismic Ground Vibration Analysis",
    content:
      "Propagation of seismic waves created by structural debris in the soil can be studied to determine the potential negative effects of the demolition on neighboring structures and underground infrastructure such as gas pipelines or subways.",
  },
  {
    title: "Dust Analysis",
    content:
      "Dust generated by demolition is a challenging environmental hazard and common nuisance to the local community. This is especially the case for controlled collapse demolitions that can produce a large amount of particulate all at once. we can estimate the size, speed, and direction of dust generated by controlled collapse demolitions so you can reduce environmental impacts.",
  },
  {
    title: "Noise Modeling",
    content:
      "Noise generated on demolition job-sites is a common discussion between demolition contractors, property owners, and the local community. To ensure public safety and address concerns of extreme noise, DEEPAM Engineers can provide estimates for sound intensity in dB due to the explosive process at the different diameters from the demolition site.",
  },
];

export default EXPERTIES;
